spring:
 thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5
 profiles:
   active: local

mybatis:
     type-aliases-package: lrdong.module.bean
     mapper-locations: classpath:lrdong/module/dao/*.xml

logging:
  config: classpath:logback-boot.xml

