package lrdong.module.dao;

import java.util.List;
import lrdong.module.bean.SysRolePrivilege;
import lrdong.module.bean.SysRolePrivilegeCriteria;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int countByExample(SysRolePrivilegeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    int insertSelective(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbggenerated
     */
    List<SysRolePrivilege> selectByExample(SysRolePrivilegeCriteria example);
}